spring:
  application:
    name: service-pise
  cloud:
    gateway:
      routes:
        - id: customer-service
          predicates:
            - Path=/api/v1/customer/**
          uri: http://www.mocky.io/v2/5cd07d623200000f0000fd00
          filters:
            - PreOauth2SSOGatewayFilter
  security:
    oauth2:
      client:
        registration:
          uaa:
            client-id: 123456789
            client-secret: 123456789
            authorization-grant-type: client_credentials
        provider:
          uaa:
            token-uri: https://yourhost.com/oauth/token